version: '3'

services:

  mvc:
    container_name: mvc
    image: orynbayev/docker_shop:master
    restart: always 
    environment:
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    