name: ci
      
on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ./DockerShop/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
